Repository Real-Faith-Solutions/career-executive-service-board, pull requests merged in 2023-08, with the labels that each got.

#129 refactoring auth user data
  app/Http/Controllers/AffiliationController.php
  app/Http/Controllers/AwardAndCitationController.php
  app/Http/Controllers/CaseRecordController.php
  app/Http/Controllers/ExaminationTakenController.php
  app/Http/Controllers/HealthRecordController.php
  app/Http/Controllers/IdentificationController.php
  app/Http/Controllers/OtherTrainingController.php
  app/Http/Controllers/ResearchAndStudiesController.php
  app/Http/Controllers/ScholarshipController.php
  app/Http/Controllers/WorkExperienceController.php
Labels: backend

#133 pdf file function
  .gitignore
  app/Http/Controllers/CompetencyController.php
  app/Http/Controllers/MigrationController.php
  app/Http/Controllers/PDFController.php
  app/Http/Controllers/ProfileController.php
  app/Models/PdfLinks.php
  app/Models/PersonalData.php
  database/migrations/201/2023_04_29_085859_create_profile_tblmain_pdflink_table.php
  database/migrations/201/2023_07_19_111008_create_profile_tblCESstatus_table.php
  resources/views/admin/201_profiling/view_profile/partials/pdf_files/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/pdf_files/table.blade.php
  routes/web.php
Labels: backend

#135 routing for educational attainment
  app/Http/Controllers/EducationalAttainmentController.php
  app/Http/Controllers/ProfileController.php
  resources/views/admin/201_profiling/view_profile/header.blade.php
  resources/views/admin/201_profiling/view_profile/partials/educational_attainment/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/educational_attainment/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/educational_attainment/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/educational_attainment/trashbin.blade.php
  routes/web.php
Labels: backend

#143 routing for research and studies
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/ResearchAndStudiesController.php
  resources/views/admin/201_profiling/view_profile/header.blade.php
  resources/views/admin/201_profiling/view_profile/partials/educational_attainment/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/research_and_studies/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/research_and_studies/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/research_and_studies/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/research_and_studies/trashbin.blade.php
  routes/web.php
Labels: backend

#146 routing for work experience
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/WorkExperienceController.php
  resources/views/admin/201_profiling/view_profile/header.blade.php
  resources/views/admin/201_profiling/view_profile/partials/work_experience/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/work_experience/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/work_experience/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/work_experience/trashbin.blade.php
  routes/web.php
Labels: backend

#148 routing for expertise
  app/Http/Controllers/ExpertiseController.php
  app/Http/Controllers/ProfileController.php
  resources/views/admin/201_profiling/view_profile/header.blade.php
  resources/views/admin/201_profiling/view_profile/partials/field_expertise/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/field_expertise/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/field_expertise/table.blade.php
  routes/web.php
Labels: backend

#152 145 routing for identification card
  app/Http/Controllers/IdentificationController.php
  resources/views/admin/201_profiling/view_profile/header.blade.php
  resources/views/admin/201_profiling/view_profile/partials/contact_information/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/family_profile/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/identification/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/identification/table.blade.php
  routes/web.php
Labels: backend

#154 routing for award and citation
  app/Http/Controllers/AwardAndCitationController.php
  app/Http/Controllers/ProfileController.php
  resources/views/admin/201_profiling/view_profile/header.blade.php
  resources/views/admin/201_profiling/view_profile/partials/award_and_citations/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/award_and_citations/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/award_and_citations/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/award_and_citations/trashbin.blade.php
  routes/web.php
Labels: backend

#157 routing for affiliation
  app/Http/Controllers/AffiliationController.php
  app/Http/Controllers/ProfileController.php
  resources/views/admin/201_profiling/view_profile/header.blade.php
  resources/views/admin/201_profiling/view_profile/partials/major_civic_and_professional_affiliations/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/major_civic_and_professional_affiliations/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/major_civic_and_professional_affiliations/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/major_civic_and_professional_affiliations/trashbin.blade.php
  routes/web.php
Labels: backend

#159 routing for case record
  app/Http/Controllers/CaseRecordController.php
  app/Http/Controllers/ProfileController.php
  resources/views/admin/201_profiling/view_profile/header.blade.php
  resources/views/admin/201_profiling/view_profile/partials/case_records/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/case_records/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/case_records/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/case_records/trashbin.blade.php
  routes/web.php
Labels: backend

#164 routing for eligibilty and rank tracker
  app/Http/Controllers/EligibilityAndRankTrackerController.php
  app/Http/Controllers/ProfileController.php
  resources/views/admin/201_profiling/view_profile/header.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/trashbin.blade.php
  routes/web.php
Labels: backend

#166 162 confirmation button
  public/js/confirmation.js
  public/js/profile-avatar.js
  resources/views/admin/201_profiling/view_profile/partials/family_profile/edit_children.blade.php
  resources/views/admin/201_profiling/view_profile/partials/family_profile/edit_father.blade.php
  resources/views/admin/201_profiling/view_profile/partials/family_profile/edit_mother.blade.php
  resources/views/admin/201_profiling/view_profile/partials/family_profile/edit_spouse.blade.php
  resources/views/admin/201_profiling/view_profile/partials/family_profile/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/family_profile/trashbin.blade.php
  resources/views/admin/201_profiling/view_profile/partials/personal_data/form.blade.php
  resources/views/layouts/app.blade.php
Labels: frontend

#170 169 confirmation button for other excluding health records and language dialects
  app/Http/Controllers/PDFController.php
  resources/views/admin/201_profiling/view_profile/partials/award_and_citations/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/award_and_citations/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/award_and_citations/trashbin.blade.php
  resources/views/admin/201_profiling/view_profile/partials/case_records/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/case_records/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/case_records/trashbin.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/trashbin.blade.php
  resources/views/admin/201_profiling/view_profile/partials/major_civic_and_professional_affiliations/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/major_civic_and_professional_affiliations/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/major_civic_and_professional_affiliations/trashbin.blade.php
  resources/views/admin/201_profiling/view_profile/partials/pdf_files/approvedFileTrashbin.blade.php
  resources/views/admin/201_profiling/view_profile/partials/pdf_files/declineFilesTrashbin.blade.php
  resources/views/admin/201_profiling/view_profile/partials/pdf_files/pendingFileTable.blade.php
  resources/views/admin/201_profiling/view_profile/partials/pdf_files/table.blade.php
  routes/web.php
Labels: backend

#173 view pdf for trashbin record
  app/Http/Controllers/PDFController.php
  resources/views/admin/201_profiling/view_profile/partials/pdf_files/approvedFileTrashbin.blade.php
  resources/views/admin/201_profiling/view_profile/partials/pdf_files/declineFilesTrashbin.blade.php
Labels: backend

#177 176 fixing validation for all tabs
  app/Http/Controllers/AffiliationController.php
  app/Http/Controllers/AwardAndCitationController.php
  app/Http/Controllers/CaseRecordController.php
  app/Http/Controllers/EligibilityAndRankTrackerController.php
  app/Http/Controllers/ExaminationTakenController.php
  app/Http/Controllers/ExpertiseController.php
  app/Http/Controllers/FamilyController.php
  app/Http/Controllers/LanguageController.php
  app/Http/Controllers/OtherTrainingController.php
  app/Http/Controllers/ResearchAndStudiesController.php
  app/Http/Controllers/ScholarshipController.php
  app/Http/Controllers/WorkExperienceController.php
  app/Models/Affiliations.php
  app/Models/CaseRecords.php
  app/Models/ResearchAndStudies.php
  resources/views/admin/201_profiling/view_profile/partials/award_and_citations/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/award_and_citations/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/case_records/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/case_records/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/field_expertise/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/field_expertise/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/languages_dialects/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/languages_dialects/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/research_and_studies/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/research_and_studies/table.blade.php
  routes/web.php
Labels: backend

#178 174 sending temporary credentials through email
  app/Http/Controllers/AddProfile201.php
  app/Mail/TempCred201.php
  app/Models/PersonalData.php
  app/Models/User.php
  database/migrations/2012_07_03_000000_create_profile_tblMain_table.php
  resources/views/admin/201_profiling/create_profile/form.blade.php
  resources/views/emails/tempcred201.blade.php
  routes/web.php
Labels: backend

#181 new controller for view profile 201
  app/Http/Controllers/Competency/CompetencyController.php
  app/Http/Controllers/CompetencyController.php
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/ViewProfile201Controller.php
  resources/views/admin/201_profiling/view_profile/table.blade.php
  resources/views/admin/competency/table.blade.php
  resources/views/admin/competency_managemengt_system/compentency_manager.blade.php
  resources/views/admin/dashboard.blade.php
  resources/views/admin/plantilla_management_system/plantilla_management_main_screen.blade.php
  resources/views/layouts/partials/sidebar.blade.php
  routes/web.php
Labels: backend

#186 185 competency other training management
  app/Http/Controllers/Competency/OtherTrainingManagementController.php
  app/Models/CompetencyNonCesAccreditedTraining.php
  app/Models/CompetencyTrainingProvider.php
  database/migrations/trainings/2023_06_06_100341_create_training_tblProvider_table.php
  resources/views/admin/competency/partials/training_sessions/other_management_trainings/form.blade.php
  resources/views/admin/competency/partials/training_sessions/other_management_trainings/table.blade.php
  resources/views/admin/competency/view_profile/header.blade.php
  routes/web.php
Labels: backend, frontend

#190 cities
  app/Http/Controllers/Competency/TrainingProviderManagerController.php
  app/Models/CompetencyTrainingProvider.php
  app/Models/PersonalData.php
  app/Models/ProfileLibCities.php
  app/Models/ProfileLibTblCities.php
  database/factories/ProfileLibCitiesFactory.php
  database/migrations/trainings/2023_06_06_100341_create_training_tblProvider_table.php
  database/seeders/DatabaseSeeder.php
  resources/views/admin/competency/partials/trainings_sub_module/training_provider_manager/form.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_provider_manager/table.blade.php
  resources/views/admin/competency/view_profile/header.blade.php
  routes/web.php
Labels: backend, frontend

#198 197 training venue manager crud
  app/Http/Controllers/Competency/TrainingProviderManagerController.php
  app/Http/Controllers/Competency/TrainingVenueManagerController.php
  app/Models/CompetencyTrainingVenueManager.php
  app/Models/ProfileLibCities.php
  database/migrations/trainings/2023_06_29_114251_create_traininglib_tblvenue_table.php
  resources/views/admin/competency/partials/trainings_sub_module/training_venue_manager/form.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_venue_manager/table.blade.php
  resources/views/admin/competency/view_profile/header.blade.php
  routes/web.php
Labels: backend, frontend

#200 199 update for training venue manager
  app/Http/Controllers/Competency/TrainingVenueManagerController.php
  resources/views/admin/competency/partials/trainings_sub_module/training_venue_manager/edit.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_venue_manager/table.blade.php
  routes/web.php
Labels: backend, frontend

#206 fix
  app/Models/Permission.php
  app/Models/Role.php
  app/Models/User.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2023_08_14_101442_create_roles_table.php
  database/migrations/2023_08_14_110340_create_permissions_table.php
Labels: backend

#209 try fix
  app/Models/Permission.php
  app/Models/Role.php
  app/Models/User.php
  database/migrations/201/2023_07_25_152647_create_profile_tblLanguages_table.php
  database/migrations/2023_08_14_111302_create_role_users_table.php
Labels: backend

#212 fix on test
  tests/Feature/ExampleTest.php
Labels: backend

#214 fixed
  tests/Feature/ExampleTest.php
Labels: backend

#217 215 user portal part3
  app/Http/Controllers/AddProfile201.php
  app/Models/User.php
  app/Providers/AdminPermissionsComposerServiceProvider.php
  config/app.php
  resources/views/admin/dashboard.blade.php
  resources/views/layouts/partials/header.blade.php
Labels: backend, frontend

#219 218 users portal part4
  app/Providers/AdminPermissionsComposerServiceProvider.php
  public/js/profile-avatar.js
  resources/views/admin/201_profiling/view_profile/partials/personal_data/form.blade.php
  resources/views/layouts/partials/header.blade.php
  resources/views/layouts/partials/sidebar.blade.php
Labels: backend, frontend

#222 changing competency layout
  app/Http/Controllers/Competency/ContactInformationController.php
  app/Http/Controllers/Competency/OtherTrainingManagementController.php
  app/Http/Controllers/Competency/TrainingProviderManagerController.php
  app/Http/Controllers/Competency/TrainingVenueManagerController.php
  resources/views/admin/competency/partials/personal_information/contact_information.blade.php
  resources/views/admin/competency/partials/training_sessions/other_management_trainings/table.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_provider_manager/edit.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_provider_manager/form.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_provider_manager/table.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_provider_manager/trashbin.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_venue_manager/edit.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_venue_manager/form.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_venue_manager/table.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_venue_manager/trashbin.blade.php
  resources/views/admin/competency/view_profile/header.blade.php
  resources/views/admin/competency/view_profile/table.blade.php
  routes/web.php
Labels: backend, frontend

#226 225 training category
  app/Http/Controllers/Competency/TrainingCategoryController.php
  app/Models/TrainingLibCategory.php
  database/factories/TrainingLibCategoryFactory.php
  database/migrations/trainings/2023_06_29_100433_create_traininglib_tblcategory_table.php
  database/seeders/DatabaseSeeder.php
  resources/views/admin/competency/partials/training_type_library/training_category/edit.blade.php
  resources/views/admin/competency/partials/training_type_library/training_category/form.blade.php
  resources/views/admin/competency/partials/training_type_library/training_category/table.blade.php
  resources/views/admin/competency/partials/training_type_library/training_category/trashbin.blade.php
  resources/views/admin/competency/view_profile/header.blade.php
  resources/views/admin/competency/view_profile/table.blade.php
  routes/web.php
Labels: backend, frontend

#228 227 training secretariat
  app/Http/Controllers/Competency/TrainingCategoryController.php
  app/Http/Controllers/Competency/TrainingSecretariatController.php
  app/Models/TrainingSecretariat.php
  database/migrations/trainings/2023_08_22_135426_create_training_secretariat_table.php
  resources/views/admin/competency/partials/training_type_library/training_secretariat/edit.blade.php
  resources/views/admin/competency/partials/training_type_library/training_secretariat/form.blade.php
  resources/views/admin/competency/partials/training_type_library/training_secretariat/table.blade.php
  resources/views/admin/competency/partials/training_type_library/training_secretariat/trashbin.blade.php
  resources/views/admin/competency/view_profile/header.blade.php
  routes/web.php
Labels: backend, frontend

#230 229 competency field specialization
  app/Http/Controllers/Competency/FieldSpecializationController.php
  app/Models/ProfileLibTblExpertiseGen.php
  database/factories/TrainingSecretariatFactory.php
  database/migrations/201/2023_05_14_032031_create_profilelib_tblExpertiseGen_table.php
  database/seeders/DatabaseSeeder.php
  resources/views/admin/competency/partials/training_type_library/expertise_specialization/edit.blade.php
  resources/views/admin/competency/partials/training_type_library/expertise_specialization/form.blade.php
  resources/views/admin/competency/partials/training_type_library/expertise_specialization/table.blade.php
  resources/views/admin/competency/partials/training_type_library/expertise_specialization/trashbin.blade.php
  resources/views/admin/competency/view_profile/header.blade.php
  routes/web.php
Labels: backend, frontend

#231 220 edit personal data
  app/Http/Controllers/AddProfile201.php
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/ViewProfile201Controller.php
  public/js/form-interaction-validation.js
  resources/views/admin/201_profiling/create_profile/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/personal_data/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/personal_data/form.blade.php
  routes/web.php
Labels: backend, frontend

#233 232 change password
  app/Http/Controllers/ProfileController.php
  app/Models/User.php
  resources/views/admin/201_profiling/view_profile/partials/personal_data/settings.blade.php
  resources/views/layouts/partials/header.blade.php
  routes/web.php
Labels: backend

#239 238 fixing encoder for all controllers
  app/Http/Controllers/AddAddress201.php
  app/Http/Controllers/AddProfile201.php
  app/Http/Controllers/AddressController.php
  app/Http/Controllers/AffiliationController.php
  app/Http/Controllers/AwardAndCitationController.php
  app/Http/Controllers/CaseRecordController.php
  app/Http/Controllers/ContactInfoController.php
  app/Http/Controllers/EducationalAttainmentController.php
  app/Http/Controllers/EligibilityAndRankTrackerController.php
  app/Http/Controllers/ExaminationTakenController.php
  app/Http/Controllers/ExpertiseController.php
  app/Http/Controllers/FamilyController.php
  app/Http/Controllers/HealthRecordController.php
  app/Http/Controllers/IdentificationController.php
  app/Http/Controllers/IndigenousGroupController.php
  app/Http/Controllers/LanguageController.php
  app/Http/Controllers/MedicalHistoryController.php
  app/Http/Controllers/OfficeManagerController.php
  app/Http/Controllers/OtherTrainingController.php
  app/Http/Controllers/PDFController.php
  app/Http/Controllers/PWDController.php
  app/Http/Controllers/PersonalDataController.php
  app/Http/Controllers/PlantillaController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/ProfileLibTblEducDegreeController.php
  app/Http/Controllers/ProfileLibTblEducMajorController.php
  app/Http/Controllers/ProfileLibTblEducSchoolController.php
  app/Http/Controllers/RecordStatusController.php
  app/Http/Controllers/ReligionController.php
  app/Http/Controllers/ResearchAndStudiesController.php
  app/Http/Controllers/ScholarshipController.php
  app/Http/Controllers/TitleController.php
  app/Http/Controllers/ViewProfile201Controller.php
  app/Http/Controllers/WorkExperienceController.php
  first_name
  last_name
  middle_name
Labels: backend

#240 236 change password part2
  app/Http/Controllers/ProfileController.php
  public/js/form-interaction-validation.js
  resources/views/admin/201_profiling/view_profile/partials/identification/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/personal_data/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/personal_data/settings.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/partials/header.blade.php
  routes/web.php
Labels: backend, frontend

#242 237 resource speaker
  app/Http/Controllers/Competency/ResourceSpeakerController.php
  app/Models/PersonalData.php
  app/Models/ResourceSpeaker.php
  database/migrations/trainings/2023_06_29_100411_create_training_tblSpeakers_table.php
  resources/views/admin/competency/partials/trainings_sub_module/resource_speaker/edit.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/resource_speaker/form.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/resource_speaker/table.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/resource_speaker/trashbin.blade.php
  resources/views/admin/competency/view_profile/header.blade.php
  routes/web.php
Labels: backend, frontend

#244 241 email changes and additions
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Requests/AddProfile201Req.php
  app/Mail/TempCred201.php
  public/js/form-interaction-validation.js
  public/js/medical-history.js
  public/js/resend-email.js
  resources/views/admin/201_profiling/create_profile/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/personal_data/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/work_experience/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/work_experience/form.blade.php
  resources/views/emails/tempcred201.blade.php
  resources/views/forgotPassword.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/login.blade.php
  routes/web.php
Labels: backend, frontend

#245 243 adding new features for pdf files max file size audit logs
  app/Http/Controllers/ApprovedFileController.php
  app/Http/Controllers/PDFController.php
  app/Models/ApprovedFile.php
  app/Models/PersonalData.php
  database/migrations/2023_08_25_154616_create_approved_file_table.php
  resources/views/admin/201_profiling/view_profile/partials/pdf_files/approveFileTable.blade.php
  resources/views/admin/201_profiling/view_profile/partials/pdf_files/pendingFileTable.blade.php
  routes/web.php
Labels: backend, frontend

#251 247 validation adjustments
  app/Http/Controllers/ProfileController.php
  public/js/form-interaction-validation.js
  resources/views/admin/201_profiling/create_profile/form.blade.php
  resources/views/admin/201_profiling/view_profile/table.blade.php
Labels: backend, frontend

#250 249 award and citation validation adjustment
  app/Http/Controllers/AwardAndCitationController.php
  app/Http/Controllers/EligibilityAndRankTrackerController.php
  resources/views/admin/201_profiling/view_profile/partials/case_records/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/case_records/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/health_records/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/major_civic_and_professional_affiliations/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/major_civic_and_professional_affiliations/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/other_management_trainings/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/other_management_trainings/form.blade.php
Labels: backend

#255 252 some changes for expertise specialization
  app/Http/Controllers/ExpertiseController.php
  app/Models/PersonalData.php
  app/Models/ProfileLibTblExpertiseSpec.php
  app/Models/ProfileTblExpertise.php
  database/seeders/DatabaseSeeder.php
  database/seeders/ProfileLibTblAppAuthoritySeeder.php
  database/seeders/ProfileLibTblCesStatusAccSeeder.php
  database/seeders/ProfileLibTblCesStatusSeeder.php
  database/seeders/ProfileLibTblCesStatusTypeSeeder.php
  database/seeders/ProfileLibTblEducDegreeSeeder.php
  database/seeders/ProfileLibTblEducMajorSeeder.php
  database/seeders/ProfileLibTblEducSchoolSeeder.php
  database/seeders/ProfileLibTblExamRefSeeder.php
  database/seeders/ProfileLibTblExpertiseSpecSeeder.php
  database/seeders/ProfileLibTblLanguageRefSeeder.php
  resources/views/admin/201_profiling/view_profile/partials/field_expertise/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/field_expertise/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/field_expertise/trashbin.blade.php
  routes/web.php
Labels: backend

#257 256 adjustment for language and dialect
  app/Http/Controllers/LanguageController.php
  app/Models/PersonalData.php
  app/Models/ProfileLibTblLanguageRef.php
  app/Models/ProfileTblLanguages.php
  resources/views/admin/201_profiling/view_profile/partials/languages_dialects/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/languages_dialects/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/languages_dialects/trashbin.blade.php
  routes/web.php
Labels: backend, frontend

#258 254 roles and permissions part2
  database/seeders/PermissionsTableSeeder.php
  database/seeders/RolesTableSeeder.php
  permissions.txt
  permissions_agency_hr_operator.txt
  permissions_cesb_operator.txt
  permissions_cespes_operator.txt
  permissions_power_user.txt
  permissions_rank_officer.txt
  permissions_training_officer.txt
  permissions_user.txt
Labels: backend, frontend
