Repository Real-Faith-Solutions/career-executive-service-board, pull requests merged in 2023-09, with the labels that each got.

#263 261 roles and permissions part3
  database/seeders/DefaultAccounts.php
Labels: backend

#270 268 roles and permissions part5
  app/Http/Controllers/RolesController.php
  app/Models/User.php
  public/js/change-role.js
  public/js/languages.js
  resources/views/admin/rights_management/user_roles.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: backend, frontend

#272 266 adding ces training
  app/Http/Controllers/Competency/OtherTrainingManagementController.php
  app/Http/Controllers/Competency/TrainingParticipantsController.php
  app/Http/Controllers/EligibilityAndRankTrackerController.php
  app/Http/Controllers/TrainingSessionController.php
  app/Models/PersonalData.php
  app/Models/ProfileLibTblCesStatus.php
  app/Models/TrainingParticipants.php
  database/migrations/trainings/2023_06_07_120112_create_training_tblparticipants_table.php
  resources/views/admin/competency/partials/ces_training_201/edit.blade.php
  resources/views/admin/competency/partials/ces_training_201/form.blade.php
  resources/views/admin/competency/partials/ces_training_201/table.blade.php
  resources/views/admin/competency/partials/ces_training_201/trashbin.blade.php
  resources/views/admin/competency/partials/other_management_trainings/edit.blade.php
  resources/views/admin/competency/partials/other_management_trainings/form.blade.php
  resources/views/admin/competency/partials/other_management_trainings/table.blade.php
  resources/views/admin/competency/partials/other_management_trainings/trashbin.blade.php
  resources/views/admin/competency/partials/training_session/edit.blade.php
  resources/views/admin/competency/partials/training_session/form.blade.php
  resources/views/admin/competency/partials/training_session/table.blade.php
  resources/views/admin/competency/partials/training_session/trashbin.blade.php
  resources/views/admin/competency/view_profile/table.blade.php
  routes/web.php
Labels: backend, frontend

#273 271 roles and permissions part6
  app/Http/Controllers/RolesController.php
  resources/views/admin/rights_management/permissions.blade.php
  resources/views/admin/rights_management/role_permissions.blade.php
  resources/views/admin/rights_management/roles.blade.php
  routes/web.php
Labels: backend, frontend

#282 bug
  app/Http/Controllers/TrainingSessionController.php
Labels: backend

#289 284 roles and permissions part8
  app/Http/Controllers/Competency/CompetencyController.php
  app/Http/Controllers/PermissionsController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/RolesController.php
  app/Providers/AdminPermissionsComposerServiceProvider.php
  database/factories/UserFactory.php
  resources/views/admin/competency/view_profile/table.blade.php
  resources/views/admin/dashboard.blade.php
  resources/views/admin/rights_management/role_permissions.blade.php
  resources/views/admin/rights_management/roles.blade.php
  resources/views/admin/rights_management/user_roles.blade.php
  routes/web.php
Labels: backend, frontend

#292 291 mailing address in competency
  app/Http/Controllers/Competency/ContactInformationController.php
  app/Http/Controllers/Competency/TrainingCategoryController.php
  app/Http/Controllers/Competency/TrainingProviderManagerController.php
  app/Http/Controllers/Competency/TrainingSecretariatController.php
  app/Http/Controllers/Competency/TrainingVenueManagerController.php
  app/Http/Controllers/MailingAddressController.php
  resources/views/admin/competency/partials/personal_information/contact_information.blade.php
Labels: frontend

#294 293 fixing validation in competency
  app/Http/Controllers/Competency/CompetencyCesTrainingController.php
  app/Http/Controllers/Competency/ResourceSpeakerController.php
  app/Http/Controllers/Competency/TrainingProviderManagerController.php
  app/Http/Controllers/Competency/TrainingVenueManagerController.php
  app/Models/TrainingSession.php
  resources/views/admin/competency/partials/ces_training_201/table.blade.php
  resources/views/admin/competency/partials/training_session/participant_list.blade.php
  resources/views/admin/competency/partials/training_session/trashbin.blade.php
  resources/views/admin/competency/partials/training_type_library/expertise_specialization/trashbin.blade.php
  resources/views/admin/competency/partials/training_type_library/training_category/trashbin.blade.php
  resources/views/admin/competency/partials/training_type_library/training_secretariat/trashbin.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/resource_speaker/trashbin.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_provider_manager/edit.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_provider_manager/form.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_venue_manager/edit.blade.php
  resources/views/admin/competency/partials/trainings_sub_module/training_venue_manager/form.blade.php
  routes/web.php
Labels: backend

#295 290 roles and permissions part9
  app/Http/Kernel.php
  app/Http/Middleware/CheckPermission.php
  resources/views/layouts/partials/sidebar.blade.php
  routes/web.php
Labels: backend

#298 296 competency address
  app/Http/Controllers/ContactInfoController.php
  database/seeders/DatabaseSeeder.php
  public/js/competency-mailing-address.js
  public/js/location-api-integration.js
  resources/views/admin/competency/partials/personal_information/contact_information.blade.php
  resources/views/layouts/app.blade.php
Labels: backend, frontend

#301 300 competency report
  app/Http/Controllers/Competency/CompetencyReportController.php
  composer.json
  composer.lock
  config/dompdf.php
  resources/views/admin/competency/reports/training_provider_report.blade.php
  resources/views/admin/competency/reports/training_provider_report_pdf.blade.php
  resources/views/layouts/partials/sidebar.blade.php
  routes/web.php
Labels: backend, frontend

#303 competency general report
  app/Http/Controllers/Competency/CompetencyReportController.php
  resources/views/admin/competency/reports/general_report.blade.php
  resources/views/admin/competency/reports/general_report_pdf.blade.php
  resources/views/layouts/partials/sidebar.blade.php
  routes/web.php
Labels: backend, frontend

#305 299 competency permissions
  database/seeders/PermissionsTableSeeder.php
  database/seeders/RolesTableSeeder.php
  permissions.txt
  permissions_agency_hr_operator.txt
  permissions_cesb_operator.txt
  permissions_cespes_operator.txt
  permissions_power_user.txt
  permissions_rank_officer.txt
  permissions_training_officer.txt
  routes/web.php
Labels: backend, frontend

#306 304 training venue manager reports
  app/Http/Controllers/Competency/CompetencyController.php
  app/Http/Controllers/Competency/CompetencyReportController.php
  app/Http/Controllers/ProfileController.php
  resources/views/admin/competency/reports/training_venue_manager_report.blade.php
  resources/views/admin/competency/reports/training_venue_manager_report_pdf.blade.php
  resources/views/layouts/partials/sidebar.blade.php
  routes/web.php
Labels: backend, frontend

#309 299 competency permissions
  app/Http/Controllers/PermissionsController.php
  app/Http/Controllers/RolesController.php
  resources/views/admin/rights_management/permissions.blade.php
  resources/views/admin/rights_management/role_permissions_competency.blade.php
  routes/web.php
Labels: backend

#316 eris
  app/Http/Controllers/Competency/CompetencyReportController.php
  app/Http/Controllers/ERIS/ErisProfileController.php
  app/Models/Eris/ErisTblMain.php
  database/migrations/erad/2023_06_29_134410_create_erad_tblMain_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/ErisTblMainSeeder.php
  resources/views/admin/eris/header.blade.php
  resources/views/admin/eris/view_profile/table.blade.php
  resources/views/layouts/partials/sidebar.blade.php
  routes/web.php
Labels: backend, frontend

#318 314 all caps input and proper on db
  app/Http/Controllers/ProfileController.php
  resources/views/admin/201_profiling/create_profile/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/contact_information/table.blade.php
Labels: frontend

#319 317 eris written exam
  app/Http/Controllers/ERIS/WrittenExamController.php
  app/Models/Eris/ErisTblMain.php
  app/Models/Eris/WrittenExam.php
  app/Models/SpouseRecords.php
  app/Models/TrainingSecretariat.php
  database/migrations/erad/2023_06_28_134410_create_erad_tblMain_table.php
  database/migrations/erad/2023_06_29_140913_create_erad_tblWExam_table.php
  database/migrations/trainings/2023_08_22_135426_create_training_secretariat_table.php
  resources/views/admin/eris/header.blade.php
  resources/views/admin/eris/partials/written_exam/edit.blade.php
  resources/views/admin/eris/partials/written_exam/form.blade.php
  resources/views/admin/eris/partials/written_exam/table.blade.php
  resources/views/admin/eris/view_profile/table.blade.php
  routes/web.php
Labels: backend, frontend

#323 322 rapid validation
  app/Http/Controllers/ERIS/RapidValidationController.php
  app/Models/Eris/ErisTblMain.php
  app/Models/Eris/RapidValidation.php
  database/migrations/erad/2023_06_29_140609_create_erad_tblRVP_table.php
  resources/views/admin/eris/header.blade.php
  resources/views/admin/eris/partials/rapid_validation/edit.blade.php
  resources/views/admin/eris/partials/rapid_validation/form.blade.php
  resources/views/admin/eris/partials/rapid_validation/table.blade.php
  routes/web.php
Labels: backend, frontend

#326 324 in depth validation
  app/Http/Controllers/ERIS/InDepthValidationController.php
  app/Models/Eris/ErisTblMain.php
  app/Models/Eris/InDepthValidation.php
  database/migrations/erad/2023_06_29_134018_create_erad_tblIVP_table.php
  resources/views/admin/eris/header.blade.php
  resources/views/admin/eris/partials/in_depth_validation/edit.blade.php
  resources/views/admin/eris/partials/in_depth_validation/form.blade.php
  resources/views/admin/eris/partials/in_depth_validation/table.blade.php
  routes/web.php
Labels: backend, frontend

#328 327 panel board interview
  app/Http/Controllers/ERIS/PanelBoardInterviewController.php
  app/Models/Eris/ErisTblMain.php
  app/Models/Eris/PanelBoardInterview.php
  database/migrations/erad/2023_06_29_135734_create_erad_tblPBOARD_table.php
  resources/views/admin/eris/header.blade.php
  resources/views/admin/eris/partials/panel_board_interview/edit.blade.php
  resources/views/admin/eris/partials/panel_board_interview/form.blade.php
  resources/views/admin/eris/partials/panel_board_interview/table.blade.php
  routes/web.php
Labels: backend, frontend

#330 329 board interview
  app/Http/Controllers/ERIS/BoardInterviewController.php
  app/Models/BoardInterview.php
  app/Models/Eris/BoardInterView.php
  app/Models/Eris/ErisTblMain.php
  database/migrations/erad/2023_06_29_133641_create_erad_tblBOARD_table.php
  resources/views/admin/eris/header.blade.php
  resources/views/admin/eris/partials/board_interview/edit.blade.php
  resources/views/admin/eris/partials/board_interview/form.blade.php
  resources/views/admin/eris/partials/board_interview/table.blade.php
  routes/web.php
Labels: backend, frontend

#332 331 eris rank tracker
  app/Http/Controllers/ERIS/RankTrackerController.php
  app/Models/Eris/ErisTblMain.php
  app/Models/Eris/LibraryRankTracker.php
  app/Models/Eris/RankTracker.php
  database/migrations/erad/2023_06_29_132720_create_erad_libRankTracker_table.php
  database/migrations/erad/2023_06_29_134018_create_erad_tblIVP_table.php
  database/migrations/erad/2023_06_29_140110_create_erad_tblranktracker_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/LibraryRankTrackerSeeder.php
  resources/views/admin/eris/header.blade.php
  resources/views/admin/eris/partials/rank_tracker/edit.blade.php
  resources/views/admin/eris/partials/rank_tracker/form.blade.php
  resources/views/admin/eris/partials/rank_tracker/table.blade.php
  routes/web.php
Labels: backend, frontend

#335 eris routing conflict solved
  resources/views/admin/eris/view_profile/table.blade.php
  routes/web.php
Labels: bug

#337 336 eris add new profile
  app/Http/Controllers/ERIS/ErisProfileController.php
  app/Models/Eris/ErisTblMain.php
  database/migrations/erad/2023_06_28_134410_create_erad_tblMain_table.php
  resources/views/admin/eris/header.blade.php
  resources/views/admin/eris/view_profile/add_new_profile/edit.blade.php
  resources/views/admin/eris/view_profile/add_new_profile/form.blade.php
  resources/views/admin/eris/view_profile/table.blade.php
  routes/web.php
Labels: backend, frontend

#339 338 eris integration to 201
  app/Http/Controllers/ERIS/ErisProfileController.php
  app/Http/Controllers/ERIS/WrittenExamController.php
  app/Http/Controllers/EligibilityAndRankTrackerController.php
  app/Models/Eris/WrittenExam.php
  database/migrations/erad/2023_06_29_140913_create_erad_tblWExam_table.php
  database/seeders/DatabaseSeeder.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/assessment_center_table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/board_interview_table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/validation_table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/written_exam_tabe.blade.php
  resources/views/admin/eris/partials/written_exam/form.blade.php
  resources/views/admin/eris/view_profile/add_new_profile/form.blade.php
  routes/web.php
Labels: backend, frontend

#341 340 competency trainig session adding participant
  app/Http/Controllers/CESTraining201Controller.php
  app/Http/Controllers/Competency/CompetencyCesTrainingController.php
  app/Http/Controllers/Competency/TrainingParticipantsController.php
  app/Http/Controllers/ERIS/ErisProfileController.php
  app/Http/Controllers/TrainingSessionController.php
  app/Models/TrainingParticipants.php
  app/Models/TrainingSession.php
  database/migrations/trainings/2023_06_07_120112_create_training_tblparticipants_table.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/written_exam_tabe.blade.php
  resources/views/admin/competency/partials/training_participant/participant_edit.blade.php
  resources/views/admin/competency/partials/training_participant/participant_form.blade.php
  resources/views/admin/competency/partials/training_participant/participant_list.blade.php
  resources/views/admin/competency/partials/training_participant/participant_trashbin.blade.php
  routes/web.php
Labels: backend, frontend

#343 displaying latest ces status
  app/Http/Controllers/Competency/CompetencyCesTrainingController.php
  app/Http/Controllers/Competency/TrainingParticipantsController.php
  app/Http/Controllers/EligibilityAndRankTrackerController.php
  app/Http/Controllers/TrainingSessionController.php
  resources/views/admin/competency/partials/training_participant/participant_list.blade.php
  resources/views/admin/competency/partials/training_participant/participant_trashbin.blade.php
Labels: backend

#345 313 two factor authentication
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Kernel.php
  app/Http/Middleware/VerifyEmailAndDevice.php
  app/Mail/ConfirmationCodeMail.php
  app/Models/DeviceVerification.php
  app/Models/User.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2023_09_21_105426_create_device_verification_table.php
  public/js/form-interaction-validation.js
  resources/views/admin/201_profiling/view_profile/partials/personal_data/settings.blade.php
  resources/views/admin/confirm_email.blade.php
  resources/views/emails/two_factor_authentication.blade.php
  resources/views/layouts/app.blade.php
  resources/views/login.blade.php
  routes/web.php
Labels: backend, frontend

#346 changes
  app/Http/Controllers/CESTraining201Controller.php
  app/Http/Controllers/Competency/CompetencyCesTrainingController.php
  app/Http/Controllers/Competency/TrainingParticipantsController.php
  app/Http/Controllers/EligibilityAndRankTrackerController.php
  app/Http/Controllers/LatestCesStatusController.php
  resources/views/admin/201_profiling/view_profile/partials/ces_trainings/edit.blade.php
  resources/views/admin/201_profiling/view_profile/partials/ces_trainings/form.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/table.blade.php
  resources/views/admin/201_profiling/view_profile/partials/eligibility_and_rank_tracker/trashbin.blade.php
  resources/views/admin/competency/partials/ces_training_201/edit.blade.php
  resources/views/admin/competency/partials/training_participant/participant_edit.blade.php
  routes/web.php
Labels: backend

#350 348 migration going back to the past
  app/Http/Controllers/Competency/CompetencyOtherTrainingManagementController.php
  app/Http/Controllers/Competency/ResourceSpeakerController.php
  app/Http/Controllers/Competency/TrainingProviderManagerController.php
  app/Http/Controllers/Competency/TrainingVenueManagerController.php
  app/Http/Controllers/ERIS/RankTrackerController.php
  app/Http/Controllers/TrainingSessionController.php
  app/Models/CompetencyNonCesAccreditedTraining.php
  app/Models/CompetencyTrainingProvider.php
  app/Models/CompetencyTrainingVenueManager.php
  app/Models/PersonalData.php
  app/Models/ResourceSpeaker.php
  app/Models/TrainingSession.php
  database/migrations/trainings/2023_06_06_100341_create_training_tblProvider_table.php
  database/migrations/trainings/2023_06_06_100411_create_training_tblSpeakers_table.php
  database/migrations/trainings/2023_06_06_114251_create_traininglib_tblvenue_table.php
  database/migrations/trainings/2023_06_07_120025_create_training_tblSessions_table.php
  database/migrations/trainings/2023_06_29_100258_create_training_tblOtherAccre_table.php
Labels: backend

#349 347 plantilla permissions
  app/Http/Controllers/PermissionsController.php
  app/Http/Controllers/RolesController.php
  database/seeders/PermissionsTableSeeder.php
  database/seeders/RolesTableSeeder.php
  permissions.txt
  permissions_agency_hr_operator.txt
  permissions_cesb_operator.txt
  permissions_cespes_operator.txt
  permissions_power_user.txt
  permissions_rank_officer.txt
  permissions_training_officer.txt
  permissions_user.txt
  resources/views/admin/rights_management/role_permissions_plantilla.blade.php
  routes/web.php
Labels: backend, frontend
